// Lista extendida de análisis
export const analysisData = [
  // A
  {
    id: 1,
    name: "ÁCIDO FÓLICO",
    price: 120.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Hematología",
    deliveryTime: "24-48 horas",
  },
  {
    id: 2,
    name: "ÁCIDO ÚRICO",
    price: 80.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Bioquímica",
    deliveryTime: "2-4 horas",
  },
  {
    id: 3,
    name: "ALANINA AMINOTRANSFERASA (ALT/TGP)",
    price: 90.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Bioquímica",
    deliveryTime: "2-4 horas",
  },
  {
    id: 4,
    name: "ALBÚMINA",
    price: 85.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Bioquímica",
    deliveryTime: "2-4 horas",
  },
  {
    id: 5,
    name: "ALDOLASA",
    price: 150.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Bioquímica",
    deliveryTime: "2-4 horas",
  },
  {
    id: 6,
    name: "ALFA 1 ANTITRIPSINA",
    price: 180.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Inmunología",
    deliveryTime: "3-5 días hábiles",
  },
  {
    id: 7,
    name: "ALFA FETOPROTEÍNA (AFP)",
    price: 200.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Marcadores Tumorales",
    deliveryTime: "24-48 horas",
  },
  {
    id: 8,
    name: "AMILASA",
    price: 110.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Bioquímica",
    deliveryTime: "2-4 horas",
  },
  {
    id: 9,
    name: "ANDROSTENEDIONA",
    price: 220.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Hormonas",
    deliveryTime: "19 días hábiles",
  },

  // B
  {
    id: 10,
    name: "BILIRRUBINA DIRECTA",
    price: 90.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Bioquímica",
    deliveryTime: "2-4 horas",
  },
  {
    id: 11,
    name: "BILIRRUBINA TOTAL",
    price: 90.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Bioquímica",
    deliveryTime: "2-4 horas",
  },
  {
    id: 12,
    name: "BETA HCG CUANTITATIVA",
    price: 150.0,
    conditions: "No",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Hormonas",
    deliveryTime: "2-4 horas",
  },

  // C
  {
    id: 13,
    name: "CALCIO",
    price: 85.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Bioquímica",
    deliveryTime: "2-4 horas",
  },
  {
    id: 14,
    name: "COLESTEROL HDL",
    price: 100.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Bioquímica",
    deliveryTime: "2-4 horas",
  },
  {
    id: 15,
    name: "COLESTEROL LDL",
    price: 100.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Bioquímica",
    deliveryTime: "2-4 horas",
  },
  {
    id: 16,
    name: "COLESTEROL TOTAL",
    price: 90.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Bioquímica",
    deliveryTime: "2-4 horas",
  },
  {
    id: 17,
    name: "CORTISOL",
    price: 130.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Hormonas",
    deliveryTime: "2-4 horas",
  },
  {
    id: 18,
    name: "CREATININA",
    price: 80.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Bioquímica",
    deliveryTime: "2-4 horas",
  },

  // D
  {
    id: 19,
    name: "DENGUE, ANTICUERPOS IGG E IGM",
    price: 250.0,
    conditions: "No",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Inmunología",
    deliveryTime: "2-4 horas",
  },
  {
    id: 20,
    name: "DÍMERO D",
    price: 280.0,
    conditions: "No",
    sample: "Plasma",
    protocol: "5 mL Plasma en Tubo Tapón Azul",
    suggestions: "",
    comments: "",
    category: "Coagulación",
    deliveryTime: "2-4 horas",
  },

  // E
  {
    id: 21,
    name: "ESTRADIOL",
    price: 140.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Hormonas",
    deliveryTime: "2-4 horas",
  },

  // F
  {
    id: 22,
    name: "FERRITINA",
    price: 150.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Hematología",
    deliveryTime: "2-4 horas",
  },
  {
    id: 23,
    name: "FIBRINÓGENO",
    price: 160.0,
    conditions: "Sí",
    sample: "Plasma",
    protocol: "5 mL Plasma en Tubo Tapón Azul",
    suggestions: "",
    comments: "",
    category: "Coagulación",
    deliveryTime: "2-4 horas",
  },
  {
    id: 24,
    name: "FOSFATASA ALCALINA",
    price: 90.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Bioquímica",
    deliveryTime: "2-4 horas",
  },

  // G  
  {
    id: 25,
    name: "GAMMA GT",
    price: 90.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Bioquímica",
    deliveryTime: "2-4 horas",
  },
  {
    id: 26,
    name: "GLUCOSA",
    price: 70.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Bioquímica",
    deliveryTime: "2-4 horas",
  },

  // H
  {
    id: 27,
    name: "HEMOGLOBINA GLUCOSILADA (HBA1C)",
    price: 180.0,
    conditions: "No",
    sample: "Sangre Total",
    protocol: "3 mL Sangre Total en Tubo EDTA",
    suggestions: "",
    comments: "",
    category: "Bioquímica",
    deliveryTime: "2-4 horas",
  },
  {
    id: 28,
    name: "HEPATITIS B SUPERFICIE AG",
    price: 180.0,
    conditions: "No",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Inmunología",
    deliveryTime: "2-4 horas",
  },
  {
    id: 29,
    name: "HEPATITIS C ANTICUERPOS",
    price: 200.0,
    conditions: "No",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Inmunología",
    deliveryTime: "2-4 horas",
  },

  // I
  {
    id: 30,
    name: "INSULINA",
    price: 160.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Hormonas",
    deliveryTime: "2-4 horas",
  },

  // L
  {
    id: 31,
    name: "LDH",
    price: 90.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Bioquímica",
    deliveryTime: "2-4 horas",
  },

  // M
  {
    id: 32,
    name: "MAGNESIO",
    price: 90.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Bioquímica",
    deliveryTime: "2-4 horas",
  },

  // P
  {
    id: 34,
    name: "PERFIL LIPÍDICO",
    price: 250.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Bioquímica",
    deliveryTime: "2-4 horas",
  },
  {
    id: 35,
    name: "PSA TOTAL",
    price: 180.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Marcadores Tumorales",
    deliveryTime: "2-4 horas",
  },
  {
    id: 36,
    name: "PSA LIBRE",
    price: 200.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Marcadores Tumorales",
    deliveryTime: "2-4 horas",
  },

  // T
  {
    id: 37,
    name: "TESTOSTERONA",
    price: 150.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Hormonas",
    deliveryTime: "2-4 horas",
  },
  {
    id: 38,
    name: "TIROTROFINA (TSH)",
    price: 140.0,
    conditions: "No",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Hormonas",
    deliveryTime: "2-4 horas",
  },
  {
    id: 39,
    name: "TIROXINA LIBRE (T4 LIBRE)",
    price: 150.0,
    conditions: "No",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Hormonas",
    deliveryTime: "2-4 horas",
  },
  {
    id: 40,
    name: "TRIIODOTIRONINA (T3)",
    price: 150.0,
    conditions: "No",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Hormonas",
    deliveryTime: "2-4 horas",
  },
  {
    id: 41,
    name: "TRIGLICÉRIDOS",
    price: 90.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Bioquímica",
    deliveryTime: "2-4 horas",
  },

  // U
  {
    id: 42,
    name: "UREA",
    price: 80.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Bioquímica",
    deliveryTime: "2-4 horas",
  },

  // V
  {
    id: 43,
    name: "VITAMINA B12",
    price: 180.0,
    conditions: "Sí",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Hematología",
    deliveryTime: "2-4 horas",
  },
  {
    id: 44,
    name: "VITAMINA D",
    price: 220.0,
    conditions: "No",
    sample: "Suero",
    protocol: "5 mL Suero en Tubo Tapón Rojo",
    suggestions: "",
    comments: "",
    category: "Hormonas",
    deliveryTime: "2-4 horas",
  },

  // Análisis de Microbiología
  {
    id: 45,
    name: "UROCULTIVO",
    price: 120.0,
    conditions: "No",
    sample: "Orina",
    protocol: "10-15 mL de orina en frasco estéril",
    suggestions: "",
    comments: "",
    category: "Microbiología",
    deliveryTime: "2-4 horas",
  },
  {
    id: 46,
    name: "COPROCULTIVO",
    price: 150.0,
    conditions: "No",
    sample: "Heces",
    protocol: "Muestra de heces en frasco estéril",
    suggestions: "",
    comments: "",
    category: "Microbiología",
    deliveryTime: "2-4 horas",
  },
  {
    id: 47,
    name: "HEMOCULTIVO",
    price: 200.0,
    conditions: "No",
    sample: "Sangre",
    protocol: "10 mL de sangre en frasco especial",
    suggestions: "",
    comments: "",
    category: "Microbiología",
    deliveryTime: "2-4 horas",
  },

  // Análisis de Hematología
  {
    id: 48,
    name: "HEMOGRAMA COMPLETO",
    price: 120.0,
    conditions: "No",
    sample: "Sangre Total",
    protocol: "3 mL Sangre Total en Tubo EDTA",
    suggestions: "",
    comments: "",
    category: "Hematología",
    deliveryTime: "2-4 horas",
  },
  {
    id: 49,
    name: "VELOCIDAD DE SEDIMENTACIÓN",
    price: 80.0,
    conditions: "No",
    sample: "Sangre Total",
    protocol: "2 mL Sangre Total en Tubo Citrato",
    suggestions: "",
    comments: "",
    category: "Hematología",
    deliveryTime: "2-4 horas",
  },
  {
    id: 50,
    name: "RETICULOCITOS",
    price: 100.0,
    conditions: "No",
    sample: "Sangre Total",
    protocol: "3 mL Sangre Total en Tubo EDTA",
    suggestions: "",
    comments: "",
    category: "Hematología",
    deliveryTime: "2-4 horas",
  }
] 